#!/bin/bash
echo ""
echo "═══════════════════════════════════════════════"
echo "   PR Review RL — Session Start"
echo "   Hackathon: Meta PyTorch OpenEnv India 2026"
echo "═══════════════════════════════════════════════"
echo "DECISIONS logged : $(wc -l < DECISIONS.md 2>/dev/null || echo 0) lines"
echo "Blog words       : $(wc -w < blog/draft.md 2>/dev/null || echo 0)"
echo "Reward logs      : $(ls rewards/*.json 2>/dev/null | wc -l) files"
echo "Tasks in bank    : $(wc -l < tasks/tasks.jsonl 2>/dev/null || echo 0)"
echo ""
echo "── Last 3 decisions ──"
tail -3 DECISIONS.md 2>/dev/null || echo "(none yet — start building!)"
echo "═══════════════════════════════════════════════"
