# Generated by codex-writer agent
# Source spec: SPEC.md
from __future__ import annotations

from typing import Any

from ..models import ReviewConfig
from .tasks import PRTask
from .tool_registry import build_domain_to_tools

# Valid risk_domains: {"security", "quality", "tests", "config", "build"}
# Valid tool names:   {"check_security", "check_quality", "check_build_and_types", "check_tests", "check_config"}

TOOL_WEIGHTS = {
    "check_security":        0.28,
    "check_quality":         0.20,
    "check_build_and_types": 0.18,
    "check_tests":           0.16,
    "check_config":          0.18,
}

# Maps each valid risk_domain to the tools that cover it
DOMAIN_TO_TOOLS: dict[str, set[str]] = {
    "security": {"check_security"},
    "quality":  {"check_quality"},
    "tests":    {"check_tests"},
    "config":   {"check_config"},
    "build":    {"check_build_and_types", "check_config"},
}


def _tool_weights(config: ReviewConfig | None = None) -> dict[str, float]:
    if config and config.tool_weights:
        return {**TOOL_WEIGHTS, **config.tool_weights}
    return TOOL_WEIGHTS


def _domain_to_tools(config: ReviewConfig | None = None) -> dict[str, set[str]]:
    dynamic = build_domain_to_tools()
    mapping = {**DOMAIN_TO_TOOLS}
    for domain, tools in dynamic.items():
        mapping.setdefault(domain, set()).update(tools)
    if config and config.enabled_tools:
        # ReviewConfig enabled_tools names external analyzers. The MCP action
        # space stays stable, so this currently keeps domain mappings intact.
        return mapping
    return mapping


def _tool_score(result: dict[str, Any] | None) -> float:
    """Extract normalised 0-1 score from a tool result dict."""
    if not result:
        return 0.0
    value = result.get("score", 0.0)
    try:
        return max(0.0, min(1.0, float(value)))
    except (TypeError, ValueError):
        return 0.0


def relevant_tools(task: PRTask, config: ReviewConfig | None = None) -> set[str]:
    """Return tool names relevant to this task's risk_domains.
    If risk_domains is empty (clean diff), return {"check_quality"} as minimal baseline.
    Otherwise union DOMAIN_TO_TOOLS[d] for each d in task.risk_domains.
    Do NOT reference "ci" or "clean".
    """
    if not task.risk_domains:
        return {"check_quality"}
    result: set[str] = set()
    domain_mapping = _domain_to_tools(config)
    for domain in task.risk_domains:
        tools = domain_mapping.get(domain)
        if tools:
            result |= tools
    return result


def aggregate_tool_scores(
    tool_results: dict[str, dict[str, Any]],
    config: ReviewConfig | None = None,
) -> float:
    """Weighted average of _tool_score() for tools present in TOOL_WEIGHTS.
    Weights renormalised over only tools actually called.
    Returns 0.0 if no known tools called. Rounded to 3 decimal places."""
    weights = _tool_weights(config)
    total = 0.0
    used_weight = 0.0
    for tool_name, result in tool_results.items():
        weight = weights.get(tool_name)
        if weight is None:
            continue
        total += weight * _tool_score(result)
        used_weight += weight

    if used_weight == 0.0:
        return 0.0
    return round(total / used_weight, 3)


def step_reward(
    task: PRTask,
    tool_name: str,
    already_called: bool,
    step_count: int,
    config: ReviewConfig | None = None,
) -> float:
    """Per-step reward for calling a tool (not submit_review/escalate).
    - submit_review/escalate -> 0.0
    - duplicate call -> -0.20
    - new call: base +0.05; +0.08 if in relevant_tools(task)
    - efficiency penalty: -0.03 per step beyond step 4
    Rounded to 3 decimal places."""
    if tool_name in {"submit_review", "escalate"}:
        return 0.0

    if already_called:
        return -0.20

    reward = 0.05
    if tool_name in relevant_tools(task, config):
        domain_bonus = 0.08
        if config:
            matching_domains = [
                domain
                for domain in task.risk_domains
                if tool_name in _domain_to_tools(config).get(domain, set())
            ]
            if matching_domains:
                priority = max(config.domain_priorities.get(domain, 1.0) for domain in matching_domains)
                domain_bonus *= priority
        reward += domain_bonus

    efficiency_start = 4
    if config:
        author_level = getattr(task, "author_level", "mid")
        depth = config.author_depth.get(author_level, 1.0)
        efficiency_start = max(2, int(round(4 * depth)))

    if step_count > efficiency_start:
        reward -= 0.03 * (step_count - efficiency_start)

    return round(reward, 3)


def terminal_reward(
    task: PRTask,
    submitted_verdict: str,
    tool_results: dict[str, dict[str, Any]],
    config: ReviewConfig | None = None,
    confidence: float | None = None,
) -> float:
    """Reward on submit_review or escalate.
    Correct + >=1 supportive tool -> 1.0 + min(0.25, evidence*0.25)
    Correct + no supportive tools -> 0.35
    escalate when expected reject/request_changes -> 0.10
    Wrong verdict -> -0.55
    """
    normalized = submitted_verdict.strip().lower()
    expected = task.expected_verdict.strip().lower()
    evidence_score = aggregate_tool_scores(tool_results, config)
    supportive_tools = len(set(tool_results) & relevant_tools(task, config))
    confidence_multiplier = 1.0
    if config and confidence is not None:
        confidence_multiplier = 0.7 + 0.3 * max(0.0, min(1.0, float(confidence)))

    if normalized == expected:
        if supportive_tools >= 1:
            return round(confidence_multiplier * (1.0 + min(0.25, evidence_score * 0.25)), 3)
        return round(confidence_multiplier * 0.35, 3)

    if normalized == "escalate" and expected in {"reject", "request_changes"}:
        return 0.10

    return -0.55


def outcome_summary(
    task: PRTask,
    tool_results: dict[str, dict[str, Any]],
    submitted_verdict: str | None = None,
    config: ReviewConfig | None = None,
) -> dict[str, Any]:
    """Returns: expected_verdict, relevant_tools (sorted list), aggregate_score, submitted_verdict."""
    return {
        "expected_verdict": task.expected_verdict,
        "relevant_tools": sorted(relevant_tools(task, config)),
        "aggregate_score": aggregate_tool_scores(tool_results, config),
        "submitted_verdict": submitted_verdict,
    }
