# Generated by codex-writer agent
# Source spec: SPEC.md
"""Run random and heuristic baselines across the full task bank.

Usage:
    python train/run_baseline.py [--seed 7] [--output rewards/baseline_eval.json]

Prints a compact ASCII comparison table to stdout and writes full JSON to --output.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from benchmarks.evaluate_baselines import evaluate_policy


def print_summary(results: dict) -> None:
    """Print a compact comparison table to stdout.

    Example output:
    Policy      Tasks  Accuracy  Mean Return
    ----------  -----  --------  -----------
    heuristic      65     0.615        0.891
    random         65     0.231        0.123
    """
    header = f"{'Policy':<12}  {'Tasks':>5}  {'Accuracy':>8}  {'Mean Return':>11}"
    sep = f"{'':{'<'}12}  {'':->5}  {'':->8}  {'':->11}"
    print(header)
    print(sep)
    for policy, data in sorted(results.items()):
        print(
            f"{policy:<12}  {data['episodes']:>5}  "
            f"{data['accuracy']:>8.3f}  {data['mean_episode_return']:>11.3f}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate random and heuristic baselines across the full task bank."
    )
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument(
        "--output",
        default=str(ROOT / "rewards" / "baseline_eval.json"),
        help="Where to write the full JSON results.",
    )
    args = parser.parse_args()

    print("Running heuristic baseline...")
    heuristic = evaluate_policy("heuristic", seed=args.seed)
    print("Running random baseline...")
    random_ = evaluate_policy("random", seed=args.seed)

    results = {"heuristic": heuristic, "random": random_}

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")

    print()
    print_summary(results)
    print(f"\nFull results written to: {output_path}")


if __name__ == "__main__":
    main()
